---
name: vpn-proxy

services:
  vpn-proxy:
    container_name: vpn-proxy
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "1080:1080"
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
      - ./danted.conf:/etc/sockd.conf:ro
    command: ["/entrypoint.sh"]
