---
name: vpn-proxy

services:
  vpn-proxy:
    container_name: vpn-proxy
    build: .
    environment:
      - EXPRESSVPN_CODE=YOUR_ACTIVATION_CODE
      - EXPRESSVPN_LOCATION=smart # Or "us", "uk", "de"
    ports:
      - 1080:1080
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
      - ./danted.conf:/etc/sockd.conf:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: unless-stopped
    privileged: true
